[package]
name = "cloudrun_test"
version = "0.2.0"
authors = ["Chris Froehlingsdorf <chris@5cf.de>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.2"
actix-web = "1.0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.12.0"
reqwest = "0.9.20"